instance_destroy( player_obj )
instance_destroy( item_base )
instance_destroy( tile_randomizer_obj )
instance_destroy( enemy_list )
instance_destroy( item_list )
instance_destroy( room_list )
instance_destroy( particle_obj )
instance_destroy( coin_obj )

ds_map_clear( fake_global.data )