var i = 0
rooms[i++] = level1
rooms[i++] = level2
rooms[i++] = level3
rooms[i++] = level4
rooms[i++] = level5
rooms[i++] = level6
rooms[i++] = level7
rooms[i++] = level8
rooms[i++] = level9
rooms[i++] = level10
rooms[i++] = level11
rooms[i++] = level12
rooms[i++] = level13